-- 1. 데이터 초기화
TRUNCATE TABLE TB_NOTICE;

-- 2. 컬럼 타입 변경 (VARCHAR2 -> NUMBER)
ALTER TABLE TB_NOTICE MODIFY NOTICE_ID NUMBER;

-- 3. 시퀀스 재설정 (삭제 후 재생성)
DROP SEQUENCE SEQ_NOTICE_ID;
CREATE SEQUENCE SEQ_NOTICE_ID START WITH 1 INCREMENT BY 1 NOCACHE;
