CREATE OR REPLACE PROCEDURE SP_ROLE_SAVE
(
    P_ROLE_ID     IN VARCHAR2,
    P_ROLE_NM     IN VARCHAR2,
    P_ROLE_DESC   IN VARCHAR2,
    P_USE_YN      IN VARCHAR2,
    P_USER_ID     IN VARCHAR2,
    P_RESULT_CODE OUT NUMBER,
    P_RESULT_MSG  OUT VARCHAR2
)
IS
    v_role_level NUMBER;
BEGIN
    SELECT NVL(MAX(ROLE_LEVEL), 0) + 1
    INTO v_role_level
    FROM TB_SYS_ROLE;

    MERGE INTO TB_SYS_ROLE T
    USING DUAL ON (T.ROLE_ID = P_ROLE_ID)
    WHEN MATCHED THEN
        UPDATE SET
            ROLE_NM = P_ROLE_NM,
            ROLE_DESC = P_ROLE_DESC,
            USE_YN = P_USE_YN,
            UPD_USER_ID = P_USER_ID,
            UPD_DT = SYSDATE
    WHEN NOT MATCHED THEN
        INSERT (ROLE_ID, ROLE_NM, ROLE_DESC, ROLE_LEVEL, USE_YN, REG_USER_ID, REG_DT, UPD_USER_ID, UPD_DT)
        VALUES (P_ROLE_ID, P_ROLE_NM, P_ROLE_DESC, v_role_level, P_USE_YN, P_USER_ID, SYSDATE, P_USER_ID, SYSDATE);

    COMMIT;
    P_RESULT_CODE := 0;
    P_RESULT_MSG := '역할이 저장되었습니다.';

EXCEPTION WHEN OTHERS THEN
    ROLLBACK;
    P_RESULT_CODE := -99;
    P_RESULT_MSG := '역할 저장 중 오류 발생: ' || SQLERRM;
END SP_ROLE_SAVE;
/
