CREATE OR REPLACE PROCEDURE SP_ROLE_GET_MENUS
(
    P_ROLE_ID IN VARCHAR2,
    O_CURSOR  OUT SYS_REFCURSOR
)
IS
BEGIN
    OPEN O_CURSOR FOR
    SELECT
        M.MENU_ID,
        M.MENU_NM,
        M.PARENT_MENU_ID,
        M.SORT_ORDER,
        LEVEL AS MENU_LEVEL,
        NVL(RM.CAN_READ, 'N') AS CAN_READ,
        NVL(RM.CAN_WRITE, 'N') AS CAN_WRITE,
        NVL(RM.CAN_DELETE, 'N') AS CAN_DELETE,
        NVL(RM.EXPORT_YN, 'N') AS EXPORT_YN
    FROM TB_SYS_MENU M
    LEFT JOIN TB_SYS_ROLE_MENU RM 
        ON M.MENU_ID = RM.MENU_ID 
        AND RM.ROLE_ID = P_ROLE_ID
    START WITH M.PARENT_MENU_ID IS NULL
    CONNECT BY PRIOR M.MENU_ID = M.PARENT_MENU_ID
    ORDER SIBLINGS BY M.SORT_ORDER;

END SP_ROLE_GET_MENUS;
/
